name: Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 14 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: artixlinux/artixlinux:latest
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sed -i 's/DownloadUser/#DownloadUser/g' /etc/pacman.conf
        pacman -Syu --noconfirm base-devel strace patchelf curl wget \
          desktop-file-utils git artix-archlinux-support llvm mesa xorg-server-xvfb
        pacman-key --init && pacman-key --populate archlinux
        printf "\n[extra]\nInclude = /etc/pacman.d/mirrorlist-arch\n" | tee -a /etc/pacman.conf
        pacman -Syu --noconfirm base-devel desmume zsync pulseaudio pulseaudio-alsa

    - name: Install debloated llvm-libs
      run: |
        LLVM="$(wget https://api.github.com/repos/Samueru-sama/llvm-libs-debloated/releases -O - \
          | sed 's/[()",{} ]/\n/g' | grep -oi "https.*very-minimal.pkg.tar.zst$" | head -1)"
        wget "$LLVM" -O ./llvm-libs.pkg.tar.zst
        pacman -U --noconfirm ./llvm-libs.pkg.tar.zst

    - name: Make AppImage
      run: |
        chmod +x ./*-appimage.sh && ./*-appimage.sh
        mkdir dist
        mv *.AppImage* dist/

    - name: Upload artifact
      uses: actions/upload-artifact@v4.4.0
      with:
        name: AppImage
        path: 'dist'

  release:
      needs: [build]
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous build
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            repo_token: ${{ secrets.GITHUB_TOKEN }}
